#!/bin/bash
#Script port scan
echo "[#]  IP DIGITADO : $1 "
echo " "
echo "[#]  SISTEMA OPERACIONAL IDENTIFICADO"
OS=$(ping -c 1 $1 | grep -i ttl  | sed -n 's/[\:-\=]/ /gp' | awk '{print $8}')

if [ $OS -lt 126 ];
then
    echo "[#]  SISTEMA LINUX"
else
    echo "[#]  SISTEMA RUINDOWS"
fi

echo "[#]  PORTAS "

for a in $(seq 65535)

  do
     `/bin/nc -z  $1  $a > /dev/null 2> /dev/null`

if [ $? -eq 0 ]

then

   echo "Porta $a Aberta"

else

   echo "Porta $a Fechada"

fi

done
