#!/bin/bash 
#Script port scan 
echo "[#]  DIGITE O  IP "
read ip
echo " "
echo "[#]  SISTEMA OPERACIONAL IDENTIFICADO"

OS=$(ping -c 1 $ip | grep -i ttl  | sed -n 's/[\:-\=]/ /gp' | awk '{print $11}')

if [ $OS -lt  126 ]

then 
    echo "[#]  SISTEMA LINUX"
else 
    echo "[#]  SISTEMA RUINDOWS"
fi

echo "[#]  PORTAS "

for a in $(seq 65535)

  do 
     `/bin/nc -z  $ip  $a > /dev/null 2> /dev/null`

if [ $? -eq 0 ]

then
  
   echo "Porta $a Aberta"
     
else 
  
   echo "Porta $a Fechada"

fi 

done  

